spring:
  profiles:
    active: ${ACTIVE_PROFILE:localhost}
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    tomcat:
      jmx-enabled: false
  h2:
    console:
      enabled: true
  liquibase:
    change-log: 'classpath:/db/changelog/master-changelog.xml'
    enabled: true
    contexts: ${LIQUIBASAE_CONTEXT:base,dev}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  cache:
    cache-names:
      - items
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html


server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
